global.greetings = [ 
	"I'm here", 
	"I've arrived", 
	"Honey… I'm home!", 
	"Buenas Dias", 
	"Oh, hello…", 
	"I'm… alive!", 
	"Thanks for letting me crash your party", 
	"Buongiorno", 
	"Hey", 
	"Hello", 
	"Hi", 
	"Howdy", 
	"Bonjour", 
	"Good day", 
	"Aloha", 
	"Yo", 
	"Namaste", 
	"Howdy-do", 
	"Cheerio", 
	"G'day", 
	"Good day", 
	"Sup", 
	"Salute", 
	"Greetings and salutations", 
	"Hola", 
	"Konichiwa", 
	"Shalom", 
	"Ni hao", 
	"Ciao", 
	"Ahoy matey", "What's up?", 
	"How's it going?", 
	"How do you do?", 
	"Top of the morning to you", 
	"Sawubona", 
	"As-salamu alaykum", 
	"Guten Tag", 
	"Hola amigo/amiga", 
	"Hello there", 
	"Hiya", 
	"How are you?", 
	"Nice to meet you", 
	"Pleased to meet you", 
	"Good morning/afternoon/evening/night", 
	"Hey there", 
	"Long time no see", 
	"Welcome back", 
	"It's good to see you again", 
	"Greetings earthling", 
	"Hello sunshine", 
	"Hey gorgeous", 
	"What's new?", 
	"What's happening?", 
	"How have you been?", 
	"Happy to see you", 
	"Glad you're here",
	"Hey, how are you holding up?",
	"You look great today",
	"Look who it is!",
	"Well, hello stranger!",
	"Hey, nice to see you again!",
	"Hello, my friend!",
	"Hey, buddy!",
	"Hi there!" 
]